import { ALLOWED_EMPLOYEES_CRS } from "@/constant/data/allowedEmployeesCRS";
import {
    Bell,
    MessageSquare,
    Users,
    FileText,
    BarChart3,
    Settings,
    FileCheck,
    DollarSign,
    Wrench,
    Package,
    ClipboardList,
    FileSpreadsheet,
    UserCheck,
    Building,
    Shield,
    Home,
    Building2,
    Calculator,
} from "lucide-react";
export const getSidebarConfig = (userLoggedInEmail) => [
    {
        id: "notification",
        label: "Notifications",
        path: "/notification",
        showBadge: true,
        type: "single",
        icon: Bell,
    },
    {
        id: "inquiry",
        label: "Customer Relations",
        type: "dropdown",
        basePath: "/inquirymanagement",
        children: [
            {
                id: "feedback",
                label: "Feedback",
                path: "/inquirymanagement/inquirylist",
                matchPaths: ["/inquirymanagement/inquirylist", "/inquirymanagement/thread"],
                icon: MessageSquare,
            },
            {
                id: "walk-in",
                label: "Walk-in",
                path: "/inquirymanagement/walk-in",
                icon: Users,
            },
            {
                id: "reports",
                label: "Reports",
                path: "/inquirymanagement/report",
                type: "floating",
                icon: BarChart3,
                children: [
                    {
                        id: "inquiries-report",
                        label: "Inquiries",
                        path: "/inquirymanagement/report/inquiries",
                        icon: FileText,
                    },
                    {
                        id: "survey-report",
                        label: "Survey",
                        path: "/inquirymanagement/report/survey",
                        icon: ClipboardList,
                    },
                    {
                        id: "walk-in-report",
                        label: "Walk-in",
                        path: "/inquirymanagement/report/walk-in",
                        icon: Users,
                    },
                ],
            },
            {
                id: "settings",
                label: "Settings",
                path: "/inquirymanagement/settings/bannersettings",
                visible: ALLOWED_EMPLOYEES_CRS.includes(userLoggedInEmail),
                icon: Settings,
            },
        ],
    },
    {
        id: "document",
        label: "Document Management",
        type: "dropdown",
        basePath: "/documentmanagement",
        children: [
            {
                id: "title-registration",
                label: "Title & Registration",
                path: "/documentmanagement/titleandregistration",
                icon: FileCheck,
            },
        ],
    },
    {
        id: "transaction",
        label: "Transaction Management",
        type: "dropdown",
        basePath: "/transaction",
        children: [
            {
                id: "receivables",
                label: "Receivables / Incoming",
                path: "/transaction/receivables/transactions",
                icon: DollarSign,
            },
            {
                id: "transaction-settings",
                label: "Settings",
                path: "/transaction/settings/markup",
                icon: Settings,
            },
            {
                id: "tools",
                label: "Tools",
                path: "/transaction/tools/check-generator/check-writer",
                icon: Wrench,
            },
        ],
    },
    // {
    //     id: "sales-dashboard",
    //     label: "Sales Dashboard",
    //     type: "dropdown",
    //     basePath: "/sales-dashboard",
    //     children: [
    //         {
    //             id: "live-inventory",
    //             label: "Live Inventory",
    //             path: "/sales-dashboard/live-inventory",
    //             icon: BarChart3,
    //         },
    //         {
    //             id: "applications",
    //             label: "Applications",
    //             path: "/sales-dashboard/applications",
    //             icon: FileText,
    //         },
    //         {
    //             id: "term-sheet",
    //             label: "Term Sheet",
    //             path: "/sales-dashboard/term-sheet",
    //             icon: Calculator,
    //         },
    //         {
    //             id: "buyers",
    //             label: "Buyers",
    //             path: "/sales-dashboard/buyers",
    //             icon: UserCheck,
    //         },
    //         {
    //             id: "sellers",
    //             label: "Sellers",
    //             path: "/sales-dashboard/sellers",
    //             icon: Users,
    //         },
    //         {
    //             id: "settings",
    //             label: "Settings",
    //             path: "/sales-dashboard/settings",
    //             icon: Settings,
    //         },
    //     ],
    // },
    {
        id: "coming-soon",
        type: "section",
        label: "Coming Soon",
        items: [
            "Property & Pricing",
            "Broker Management",
            "Sales\nManagement",
            "Property\nManagement",
            "Sales Management",
        ],
    },
    {
        id: "super-admin",
        label: "Admin Settings",
        type: "dropdown",
        basePath: "/super-admin",
        visible: ALLOWED_EMPLOYEES_CRS.includes(userLoggedInEmail),
        children: [
            {
                id: "user-rights",
                label: "User Rights & Permissions",
                path: "/super-admin/user-rights-and-permissions",
                icon: Shield,
            },
            {
                id: "property-settings",
                label: "Property Settings",
                path: "/super-admin/property-settings",
                icon: Building,
            },
        ],
    },
];
